Rework Logs content and Format
outscale/cluster-api-provider-outscale pull request #220
Opened 2023-02-01 08:45 UTC by outscale-vbr

**What type of PR is this?**
/kind cleanup  

**What this PR does / why we need it**:
Rework logs and improve logs format
Closes #219 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #219 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

2023-02-02 08:53 UTC, outscale-vbr commented
https://github.com/outscale/cluster-api-provider-outscale/pull/221 will be merge first to handle cve.
and change on trivyignore will be removed for this PR.

2023-02-09 13:56 UTC, outscale-mdr requested changes

2023-02-09 13:56 UTC, outscale-mdr commented on helm/clusterapioutscale/values.yaml
> +    backoff_steps: "1"
Another PR ? or commit ?

2023-02-09 13:56 UTC, outscale-mdr commented on capm.yaml
> +          value: "1"
Another PR ? Which issue ?

2023-02-10 08:52 UTC, outscale-vbr commented on capm.yaml
> +          value: "1"
Another commit

2023-02-10 08:52 UTC, outscale-vbr commented on helm/clusterapioutscale/values.yaml
> +    backoff_steps: "1"
another commit

2023-02-20 14:05 UTC, outscale-vbr commented
@outscale-mdr Are you ok with this PR ?

2023-02-20 14:19 UTC, outscale-mdr commented on capm.yaml
> +        - --zap-log-level=10
Still positive integer ?

2023-02-20 14:19 UTC, outscale-mdr commented on config/default/manager_auth_proxy_patch.yaml
> +        - "--zap-log-level=10"
Same

2023-02-20 14:33 UTC, outscale-vbr commented on capm.yaml
> +        - --zap-log-level=10
Yes

2023-02-20 14:34 UTC, outscale-vbr commented on config/default/manager_auth_proxy_patch.yaml
> +        - "--zap-log-level=10"
Yes

2023-02-20 14:34 UTC, outscale-mdr approved these changes

2023-02-20 16:22 UTC, merged