Add talos
outscale/cluster-api-provider-outscale pull request #264
Opened 2023-08-29 09:00 UTC by outscale-vbr

**What type of PR is this?**
/kind feature   

**What this PR does / why we need it**:
Add talos bootstrapper
**Which issue(s) this PR fixes**:
Fixes #263

2023-08-30 13:18 UTC, outscale-toa requested changes

2023-08-30 13:18 UTC, outscale-toa commented on example/talos/README.md
> +You can initialize clusterctl with credential with:
Maybe : ``` You can initialize the credentials of the clusterctl with: ```

2023-08-30 13:18 UTC, outscale-toa commented on example/talos/bastion/bastion.tf
> +      version = "0.8.2"
why not ```version = ">= 0.8.2" ``` to always get latest provider version

2023-08-31 07:52 UTC, jerome-jutteau approved these changes

2023-08-31 09:02 UTC, merged